version: '3'

services:

  {{ book_name }}:
    image: httpd:2.4.51
    container_name: {{ book_name }}_image
    volumes:
      - {{ book_remote_html }}:/usr/local/apache2/htdocs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - "traefik.http.routers.{{ book_name }}.rule=Host(`{{ book_domain }}`)"
      - traefik.http.routers.{{ book_name }}.tls=true
      - traefik.http.routers.{{ book_name }}.tls.certresolver=lets-encrypt
      - traefik.http.routers.{{ book_name }}.service={{ book_name }}
      - traefik.http.services.{{ book_name }}.loadbalancer.server.port=80
    restart: on-failure
    networks:
      - {{ network_name }}

networks:
    {{ network_name }}:
      external: true
